### ISSUE TITLE
Feature Request: Admin role won't inherit auto approval roles

### ISSUE THREAD

**Issue by Nomelas** [Ombi-app/Ombi#1628]
#### Ombi build Version:

V 3.0.2176

#### Update Branch:

Open Beta

#### Media Sever:

Plex

#### Media Server Version:

N/A

#### Operating System:

N/A

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

N/A

```

#### Problem Description:

This is more of a feature request (not sure if it's a bug or not):

It would be nice if the 'admin' role didn't automatically inherit the auto approve roles - I'd like to be able to make myself an admin, but have to still approve my own stuff (so I can set the base directory before approving)

#### Reproduction Steps:

Anyone with Admin role already has their requests auto approved even without the role enabled.

**Comment by tidusjar** [comment]
Hmmm... I'll think about it

**Comment by mattohm** [comment]
I think better would be people with auto approve having the option when
they are requesting.

**Comment by tidusjar** [comment]
I didn't want to give that responsibility to the user. Since some users don't understand the concept

**Comment by mattohm** [comment]
Those are the users you don't give auto approve permissions to ;)

**Comment by Nomelas** [comment]
@mattohm , Yes that would be even better! users with auto-approve could be able to choose the location :D

**Comment by Nomelas** [comment]
As it stands, I need to create a local user that isn't admin and log into it every time i want to make a new request, and then approve my own request after changing the base path for say, anime. then, if I want to change settings, i need to log out and log back in as the admin account.

I'd just create the requests in radarr/sonarr but they don't show up as requested in omni that way.

**Comment by tidusjar** [comment]
Maybe a new permission for users to change the root path and quality

**Comment by masau** [comment]
Permission for users to change root path and quality would be great. Not having to manually sort everything would be nice. I can for the most part trust my users to at least not sort incorrectly. Though I'd rather not have them deviating from default quality.

**Comment by bagobones** [comment]
I have a plugin pending approval for flexget that I have been using for my self for a while now.. I like the idea of the approval step allowing for a path change before download. However I thing a 'Custom" generic app is needed in both TV and Movie settings to allow download path lists to be created for it to be much use to me or other apps that use the API.

**Comment by andrewmiskell** [comment]
+1 for this ability or at least modifications to suit the use case.

We have several root folders based on the type of show (tvshows, movies, kids_tvshows, kids_movies). 

I'm an admin and my wife is a regular user with request permissions. Since I'm an admin and everything auto-approves, I never set the ability to set the root folder at selection and always have to do it after the fact (which never appears to sync up in radarr/sonarr when I do change it after the fact).

I've only been able to work around this by creating myself a secondary non-admin power-user to approve things myself and approve requests by my wife (where I can set the root folder at approval). However, a side effect of this is what I'm no longer notified via the Ombi mobile app whenever my wife requests something (since there's no device logged in as the admin account any longer).

**Comment by tidusjar** [comment]
Not stale

**Comment by twanariens** [comment]
This has taken a while, BUT Ombi now has the ability to request for a different user and also to change quality profiles / root path when an Admin does a request.

Feature request/issue will be closed
