### ISSUE TITLE
Issues: The Feature Part deux. 

### ISSUE THREAD

**Issue by goldenpipes** [Ombi-app/Ombi#2647]
Create an "report issue" button on the issues page that opens up a new page with a "Media type" (music, tv, movie.) dropdown.  Followed by "title" dropdown, then the "issue type" dropdown.  Then a comment box if necessary.  If its a tv show, have a second and third dropdown for "season" and "episode number".  Finally a comment box.

![unknown](https://user-images.githubusercontent.com/6140137/48603725-1175a680-e93d-11e8-806f-fe6f79ce5c12.png)

**Comment by goldenpipes** [comment]
https://cdn.discordapp.com/attachments/431634691670540299/512848789229273112/unknown.png

**Comment by tamburra** [comment]
Extremely agree with this to have a separate section for issues.  I have many users complaining about the same thing as are confused on how reporting issues and requesting content are in the same screen.  Especially when the top of the page says "Want to watch something that is not currently available? No problem, just search for it below and request it!" and nothing about how to report an issue.

I also use OMBI and I would love to be able to have a separate tab called Report Issue and link this to the Issues page of OMBI.

**Comment by tidusjar** [comment]
From @enchanged

First of all, thank you for this feature, I used to forget when my friends reported to me everything in chats, and it was frustrating to keep track without the proper system, but now we use Ombi Issues quite a lot.
- Mark in Progress and Mark Resolved probably should be separate buttons, right now you always have to go through the in-progress state, while the issues that require "in progress" are not that often in my case.
- Some users don't know/notice there's "In Progress" and are creating duplicate issues. It would be nice to warn the user on submitting if any user already reported same issue for same title when it's not resolved yet. Something like red message saying that (and the existing issue description) and the Submit button changes to "Submit anyway".
- I'd like to keep Issues history, but also want an option to manually remove some issues - like test issues or duplicates. 
- It would be really cool if I could remove, resolve, or in-progress issues right from the Issues list (maybe by using icons at the end of the row?) without having to go to the details. Also an indicator of whether there's a description (icon with description text tooltip on hover) or any comments (comment icon with comment count) would really help speeding things up - most of my issues are really specific, so there's rarely any comments or even descriptions, so it would be possible to speed up through a lot of issues in no time with those quick actions. 
- And even without quick actions, it would be quite useful to have "Next unresolved issue" button in the details, and maybe move the action buttons in details from the bottom to the top? It often jumps from top to bottom when poster is loading, and I usually go to details after the issue is resolved, and every time I mis-click it or have to wait, so I feel like there's some potential to making it more streamlined for those who have a lot of reports from users.

**Comment by twanariens** [comment]
Implemented into Ombi V4
