### ISSUE TITLE
Mobile view not right

### ISSUE THREAD

**Issue by damusmf** [Ombi-app/Ombi#3893]
**Describe the bug**
When viewing on mobile (pixel 3) the display is not scaling properly.  The entire page seems very left aligned instead of centered. And the buttons to choose between the new poster style or the v3 style of viewing are stuck in the top left corner and barely visible. And the poster beneath will cover up most of the words/description of the title above it.

If you change to landscape view vs portrait it somewhat fixes itself, But if you choose the v3 style of displaying titles vs the new v4 style and remain in portrait mode, the overlapping text is even wrose.

**To Reproduce**
1. go to your ombi page on your phone
2. Go to discover page
3. view the issues
4. change phone orientation to landscape
5. choose the other view type for titles
6. put phone back in portrait mode
7. view issues

**Expected behavior**
Page should scale properly on mobile. 

**Screenshots**
![image](https://user-images.githubusercontent.com/31552122/100294484-8af0f800-2f4c-11eb-8e6e-f6dfe5c75448.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Android 11

**Ombi Version (please complete the following information):**
 - Version 4.0.728.0
- Media Server Plex
- Database Type: SQLite

**Additional context**
Mobile usage is how most people are requesting things for me.  V4 is a big step up from v3 but without proper mobile view it is hard to make the switch.

**Comment by tidusjar** [comment]
Interesting, you shouldn't be able to view the V3 style of cards on this
discover in mobile view

**Comment by damusmf** [comment]
Yeah if you go to landscape mode you can see the buttons to switch the view.  Both look fine in landscape mode, portrait is where the problem comes up.  Screenshot in initial post is portrait mode with the new v4 grid view.  The following is showing the buttons, then changing to the old v3 style, then going back to portrait. This is on a pixel 3 running android 11 and just chrome browser. 

![image](https://user-images.githubusercontent.com/31552122/100319086-b68fd480-2f84-11eb-8b13-8de4032f3aef.png)

![image](https://user-images.githubusercontent.com/31552122/100319117-bee80f80-2f84-11eb-9969-4a256941c239.png)

![image](https://user-images.githubusercontent.com/31552122/100319140-c7404a80-2f84-11eb-873e-6cb4dcc6744a.png)

**Comment by tidusjar** [comment]
Oh i see, so you only get the buttons to switch the grid when in landscape mode, I get it

**Comment by damusmf** [comment]
They dont show fully until you switch to landscape mode but in the first screen shot you can see in the top left the buttons are there, they are just cut off and you only see half of what should be the right button.  It covers up the movies and popular buttons.  And those buttons and the posters dont appear to be centered.

**Comment by hirenshah** [comment]
Looks like the `@media` CSS isn't correct :(

I'm just trialling Ombi and got one of my Plex users to test the features.  She was accessing it on her mobile and her first response was:
> I'm in but the UI is awful

It has been a few years since I played around with responsive designs but I will try and troubleshoot this.  @tidusjar let me know if you've already spent some time on this :)

**Comment by tidusjar** [comment]
Yeah the grid is not suppose to be for mobile

**Comment by hirenshah** [comment]
@tidusjar Here are some views when changing the screen width using Chrome Developer Tools and some of my thoughts on each one:

780px - the minimum width when showing both the sidebar and option to switch between cards/list, because below this width, the buttons start to overlap.  May be worthwhile switching to a toggle sidebar at this point.
![780px](https://user-images.githubusercontent.com/418112/103782964-08ba2000-5030-11eb-83ab-fd54fb22cd23.png)

660px - just to show how the cards/list buttons overlaps the others:
![660px](https://user-images.githubusercontent.com/418112/103783004-153e7880-5030-11eb-86c9-56a27853daeb.png)

620px - shows the above mentioned overlap as well the cards doing something similar:
![620px](https://user-images.githubusercontent.com/418112/103783016-18396900-5030-11eb-955c-934f1e6d88e1.png)

600px (Cards) - sidebar collapses at this point (yay!) but the cards still look silly:
![600px Cards](https://user-images.githubusercontent.com/418112/103783029-1c658680-5030-11eb-8fe3-995bfb0bfaa8.png)

600px (List) - list view is no better either:
![600px List](https://user-images.githubusercontent.com/418112/103783022-1a032c80-5030-11eb-92ef-a529a4065d92.png)

**Comment by hirenshah** [comment]
> Yeah the grid is not suppose to be for mobile

But it is the only one that currently works on mobile... with the list view, there is no way of getting to the details screen because the artwork is no longer a link.

So just make sure you don't stop the grid view being available for mobiles without actually fixing the list view first :)

**Comment by hirenshah** [comment]
@tidusjar The Details view looks a lot better now following your recent updates.  The Discover view is still a bit of a mess though.

Definitely a step forward :)

**Comment by tidusjar** [comment]
I pushed an update today that resolved mainly the detail pages. It's just a work in progress, I'll continue with the discover next

**Comment by twanariens** [comment]
This has been fixed in the latest V4 version (develop)
