### ISSUE TITLE
Fails to add requests to SickChill

### ISSUE THREAD

**Issue by XanderStrike** [Ombi-app/Ombi#3930]
**Describe the bug**
Requests approved in Ombi never appear in SickChill.

**To Reproduce**

0. Verify SickChill connection settings, test successfully
1. Request a show
2. Approve the request
3. Wait a while
4. Request never appears in SickChill

**Expected behavior**
Show is successfully added to SickChill _or_ and error is surfaced to the user (if relevant)

**Logs (Logs directory where Ombi is located)**
Ombi appears to log nothing relevant:
```
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no users to send a notification for RequestApproved, for agent Mobile
```

SickChill Log:
```
2020-12-12 08:25:50 INFO :: WEBSERVER :: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher
    cur_out_dict = to_call.run()  # call function and get response
  File "/usr/lib/python3.8/site-packages/sickchill/views/api/webapi.py", line 2149, in run
    raise ApiError("Invalid Status")
sickchill.views.api.webapi.ApiError: Invalid Status
```

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu
 - Image: linuxserver/sickchill

**Ombi Version (please complete the following information):**
- Version: 3.0.5223
- Media Server: N/A (both Plex and Jellyfin)
- Database Type: sqlite

**Additional context**

#3810 sounded similar at first, but the big difference is that the test page is successful for me.

**Comment by Kinisbenis** [comment]
**Copied most parts from @XanderStrike  – thank you 
Describe the bug**
 Requests approved in Ombi never appear in SickChill.
**Steps to reproduce the behavior:**
    0. Verify SickChill connection settings, test successfully 
    1. Request a show 
    2. Approve the request 
    3. Wait a while 
    4. Request never appears in SickChill 
**Expected behavior**
Show is successfully added to SickChill
**Logs**:
_Ombi log:_
2020-12-12 19:44:56.608 +01:00 [Warning] Couldnt find the SR Season or Show, message: "Show not found"
_SickChill Log:_
2020-12-12 19:44:45 INFO :: WEBSERVER :: Traceback (most recent call last):
  AA File "/usr/lib/python3.7/dist-packages/sickchill/views/api/webapi.py", line 166, in call_dispatcher
  AA cur_out_dict = to_call.run()  # call function and get response
  AA File "/usr/lib/python3.7/dist-packages/sickchill/views/api/webapi.py", line 2181, in run
  AA raise ApiError("Invalid Status")
  AA sickchill.views.api.webapi.ApiError: Invalid Status
**Hardware**:
    • OS Architecture: Arm
    • OS:  Linux 4.1.51 #2 SMP PREEMPT Fri Aug 14 15:38:06 EDT 2020
**Ombi Version:**
    • Version: 3.0.5223 
    • Media Server: Emby 
    • Database Type: Sqlite 
**SickChill Version:**
Install: pip  Version: v2020.11.24-1  Database Version: 44.5 
Python verzió: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0] 
OS:  Linux-4.1.51-aarch64-with-debian-10.7

**Comment by kyuuk** [comment]
actually it's more of a sickchill Bug
I opened an issue there 
[#6929](https://github.com/SickChill/SickChill/issues/6929)

**Comment by TATUMTOT** [comment]
Having the same issue.

**Comment by twanariens** [comment]
Thanks for the report, we will continue this in #3810
