### ISSUE TITLE
User Filtering Issue

### ISSUE THREAD

**Issue by JuniperMS** [Ombi-app/Ombi#4539]
**Describe the bug**
When an Ombi administrator adds a movie on behalf of a user, the administrator cannot begin typing the users email address to filter down. When you do, all user accounts in the drop down disappear regardless if what you're typing matches a users email address.

**To Reproduce**
1. Select a movie.
2. Click on 'request'.
3. Navigate to 'Request on behalf of'.
4. Begin to type in a users email address.
5. All available users disappear.

**Expected behavior**
I expect for the user field to begin to narrow down. If I have a user with a username of "[johnsmith@gmail.com](mailto:johnsmith@gmail.com)", I expect to be able to begin typing "jo" and all users except for "[johnsmith@gmail.com](mailto:johnsmith@gmail.com)" disappear.

**Screenshots**
Cannot provide due to security concerns.

**Logs (Logs directory where Ombi is located)**

**Desktop (please complete the following information):**
 - Ubuntu w/ docker.

**Ombi Version (please complete the following information):**
 - Version: 4.14.2
 - Media Server: Plex
 - Database Type: MySQL

**Additional context**

**Comment by Firetop** [comment]
I have the same issue; but I should mention it appears that it was never intended to be by email; but instead by Username.
If you search by Username everything filters correctly for me on the second search; the first search always returns no results.

The reason for this is it auto-fills a Blank 'Space" before the username:

![image](https://user-images.githubusercontent.com/1971404/156954443-396c21dd-3b38-47db-8bbb-68379b4421f9.png)

If I put my curser before the name and hit "Backspace" the username shows up as expected:

![image](https://user-images.githubusercontent.com/1971404/156954631-51dfa226-a1c6-45ec-b546-87f7ff5f855c.png)

The bug is the pre-filled 'space" before you start typing; not so much the email addresses.

![image](https://user-images.githubusercontent.com/1971404/156954685-a5acdc04-64c2-42e7-9f62-d28a846080e9.png)

**Comment by JuniperMS** [comment]
My username is my email in this case, but I can search it now if I remove the space you mentioned.

**Comment by Firetop** [comment]
> My username is my email in this case, but I can search it now if I remove the space you mentioned.

I'm happy you have a workaround for now :) Hopefully this little bug will be easy to fix :)

**Comment by tidusjar** [comment]
Nice spot!

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
