### ISSUE TITLE
SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Key'

### ISSUE THREAD

**Issue by flyize** [Ombi-app/Ombi#4873]
**Describe the bug**
I'm seeing the following error over and over again in my logs.

```
2023-02-21 12:00:02.302 -05:00 [ERR] Failed executing DbCommand (4ms) [Parameters=[@p0='?' (DbType = DateTime), @p1='?' (DbType = Boolean), @p2='?', @p3='?' (Size = 6), @p4='?', @p5='?' (Size = 2), @p6='?' (DbType = Int32), @p7='?', @p8='?' (Size = 9), @p9='?' (Size = 6), @p10='?' (DbType = Int32), @p11='?' (Size = 117)], CommandType='"Text"', CommandTimeout='30']
INSERT INTO "PlexServerContent" ("AddedAt", "Has4K", "ImdbId", "Key", "Quality", "ReleaseYear", "RequestId", "TheMovieDbId", "Title", "TvDbId", "Type", "Url")
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11);
SELECT "Id"
FROM "PlexServerContent"
WHERE changes() = 1 AND "rowid" = last_insert_rowid();
2023-02-21 12:00:02.320 -05:00 [ERR] An exception occurred in the database while saving changes for context type 'Ombi.Store.Context.Sqlite.ExternalSqliteContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: PlexServerContent.Key'.
```

**To Reproduce**
- view logs

**Expected behavior**
No errors in logs

**Screenshots**
n/a

**Logs (Logs directory where Ombi is located)**
See above

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.35.8
- Media Server Plex
- Database Type: SQLite 

**Additional context**
n/a

**Comment by twanariens** [comment]
This is a more complicated issue. This either means that something went bonkers in the OmbiExternal database, or something is wrong with your Plex library.

To check where the issue lies, you need to:
- stop Ombi
- delete OmbiExternal.db
- start Ombi
- wait for the Plex sync
- check if the logs still have the error

If the error no longer shows, the issue lied in the database and we fixed it by recreating the database. If the error comes up again, then your Plex library is at fault here. Meaning that your Plex instance should provide a unique key to content. In this case it failed because there is a duplicate somewhere which is getting synced to Ombi.

**Comment by sephrat** [comment]
You will lose nothing from deleting OmbiExternal, this database is only meant as a cache so that Ombi doesn't connect to external systems (Plex, Radarr, Sonarr, ...) whenever we need some info.
Also, a less brutal solution would be to hit "Clear Data And Resync" in the Plex settings. 

Let us know if this doesn't fix it. Closing for now.
